// <auto-generated />
namespace FeatureTrackerService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_home : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_home));
        
        string IMigrationMetadata.Id
        {
            get { return "201705050239332_initial_home"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
